package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/richardimaoka/next-gqlgen-sandbox/gqlgen/graph/model"
)

// Markdown is the resolver for the markdown field.
func (r *queryResolver) Markdown(ctx context.Context) (*model.Markdown, error) {
	contents := `Googleのサービスで、

**「素早く」「簡単に」** 認証を導入！`
	return &model.Markdown{Contents: &contents}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
